### ISSUE TITLE
S-arrival time in hypo71

### ISSUE THREAD

**Issue by alebrovelli** [usgs/swarm#294] opened 2019-10-03 10:45 UTC
As mentioned in the other thread, I believe the S-arrival times are not correctly considered in hypo71.
I made an example to illustrate the problem. 
Here is the output from hypo71
![out1](https://user-images.githubusercontent.com/48241967/66115830-e5552980-e5d1-11e9-97a4-cc21876ca92d.JPG)

The picked arrival times were (from the QuakeML)
![xml](https://user-images.githubusercontent.com/48241967/66117209-67465200-e5d4-11e9-8ea0-bb1d13c5c7d6.JPG)

The P-arrival time is the same in both files, whereas (in this case) the S-time listed by hypo71 is identical to the P-arrival time. In other cases, I found that the P- and S-arrivals in the hypo71 output are different, but the S- is still incorrect when compared to the QuakeML. It seems to me that if the difference in arrival time is smaller than 1sec, the P- and S- arrivals are riported as identical to hypo71, otherwise the S-arrival is calculated as the P-time shifted by a certain number of seconds (maybe the number of seconds between P and S, minus 1?).

As for the S- arrivals that cross the minute compared to P-arrival, my interpretation of the manual is that one should add 60seconds (or a multiple of) to the S, i.e.
P-arrival 10:50 21.49
S-arrival at 10:51:12.00 should be listed as 72.00 in the hypo71 input, that is, the S-arrival occurs 72.00 seconds after the HR:MIN.
Not sure either that my interpretation is correct.

I attach also the xml and output file of my example, in case you need them.
[SwarmTest.zip](https://github.com/usgs/swarm/files/3685584/SwarmTest.zip)

Alessandro

**Comment by dnorgaard-usgs** [comment] 2019-10-09 00:36
[swarm-2.8.14-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/3705043/swarm-2.8.14-SNAPSHOT-bin.zip)

@alebrovelli Would you mind trying the attached Swarm to see if the issue is fixed?  I don't have a good test case handy at the moment.  If I don't hear back I'll try to find a test case later in the week.  (Or maybe you can export your data to files and attach here along with your SwarmMetadata.config if it has locations for the stations?)

**Comment by dnorgaard-usgs** [comment] 2019-10-24 21:41
Hi.  I believe this issue is now resolved (to go into next release) so I am closing the ticket.  However, if you are able to test and find that it is not the case, please let me know and I will reopen.

**Closed by dnorgaard-usgs** 2019-10-24 21:41 UTC
Labels: bug

**Comment by alebrovelli** [comment] 2019-10-27 21:24
Hi Diana,
I was finally able to do some testing. I confirm the snapshot you shared fixes the problem. I will test again once the new release is out. Thank you very much!
Alessandro
