### ISSUE TITLE
Hello from quebec...

### ISSUE THREAD

**Issue by virusdunil** [usgs/swarm#214] opened 2018-07-18 20:09 UTC
In the MONITOR windows...we only see current time at far right and time at beginning...Depending on the width of the window,is it possible to add 1-2-3 time/hour display  below the spectro/seismos?

Also,add color setup for webicorder backgrounds,plots color ect.
Blinking new red dot on map...when there's a lot at same place (like Kilauea) Blinks till a new one pops up...
Thanks
![display](https://user-images.githubusercontent.com/41394194/42905635-9ee216fc-8aa6-11e8-901d-d7e681cbfdf3.png)

**Comment by dnorgaard-usgs** [comment] 2018-07-23 23:16
First request is a duplicate of #78.

Would you mind clarifying your second request?  Thanks.

**Comment by dnorgaard-usgs** [comment] 2018-07-24 00:01
On first request, since there would be no corresponding grid lines (in time series they are constantly moving) that would go with the fixed time at the bottom, I am not sure it is such a good idea to add the times in the middle (start and end points are clear).  Similar issue (ticket #78) has been rejected.

**Comment by dnorgaard-usgs** [comment] 2018-11-29 05:37
Hello.  I will reopen if second issue can be clarified.  For now I am closing.

**Closed by dnorgaard-usgs** 2018-11-29 05:37 UTC
Labels: wontfix
